namespace BidiReshapeSharp.Reshaper
{
    public class ReshaperConfig
    {
        public string Language { get; set; } = "Arabic";
        public bool DeleteHarakat { get; set; } = true;
        public bool DeleteTatweel { get; set; } = false;
        public bool SupportZwj { get; set; } = true;
        public bool ShiftHarakatPosition { get; set; } = true;
        public bool UseUnshapedInsteadOfIsolated { get; set; } = false;
        public bool SupportLigatures { get; set; } = true;

        // A dictionary to represent which ligatures are enabled
        public Dictionary<string, bool> EnabledLigatures { get; set; } = new Dictionary<string, bool>
        {
            // ------------------- Begin: Ligatures Configurations ------------------ //

            // Sentences (Enabled on top)
            {"ARABIC LIGATURE BISMILLAH AR-RAHMAN AR-RAHEEM", false},
            {"ARABIC LIGATURE JALLAJALALOUHOU", false},
            {"ARABIC LIGATURE SALLALLAHOU ALAYHE WASALLAM", false},

            // Words (Enabled on top)
            {"ARABIC LIGATURE ALLAH", true},
            {"ARABIC LIGATURE AKBAR", false},
            {"ARABIC LIGATURE ALAYHE", false},
            {"ARABIC LIGATURE MOHAMMAD", false},
            {"ARABIC LIGATURE RASOUL", false},
            {"ARABIC LIGATURE SALAM", false},
            {"ARABIC LIGATURE SALLA", false},
            {"ARABIC LIGATURE WASALLAM", false},
            {"RIAL SIGN", false},

            // Letters (Enabled on top)
            {"ARABIC LIGATURE LAM WITH ALEF", true},
            {"ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE", true},
            {"ARABIC LIGATURE LAM WITH ALEF WITH HAMZA BELOW", true},
            {"ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE", true},
            {"ARABIC LIGATURE AIN WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE AIN WITH JEEM", false},
            {"ARABIC LIGATURE AIN WITH JEEM WITH MEEM", false},
            {"ARABIC LIGATURE AIN WITH MEEM", false},
            {"ARABIC LIGATURE AIN WITH MEEM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE AIN WITH MEEM WITH MEEM", false},
            {"ARABIC LIGATURE AIN WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE AIN WITH YEH", false},
            {"ARABIC LIGATURE ALEF MAKSURA WITH SUPERSCRIPT ALEF", false},
            {"ARABIC LIGATURE ALEF WITH FATHATAN", false},
            {"ARABIC LIGATURE BEH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE BEH WITH HAH", false},
            {"ARABIC LIGATURE BEH WITH HAH WITH YEH", false},
            {"ARABIC LIGATURE BEH WITH HEH", false},
            {"ARABIC LIGATURE BEH WITH JEEM", false},
            {"ARABIC LIGATURE BEH WITH KHAH", false},
            {"ARABIC LIGATURE BEH WITH KHAH WITH YEH", false},
            {"ARABIC LIGATURE BEH WITH MEEM", false},
            {"ARABIC LIGATURE BEH WITH NOON", false},
            {"ARABIC LIGATURE BEH WITH REH", false},
            {"ARABIC LIGATURE BEH WITH YEH", false},
            {"ARABIC LIGATURE BEH WITH ZAIN", false},
            {"ARABIC LIGATURE DAD WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE DAD WITH HAH", false},
            {"ARABIC LIGATURE DAD WITH HAH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE DAD WITH HAH WITH YEH", false},
            {"ARABIC LIGATURE DAD WITH JEEM", false},
            {"ARABIC LIGATURE DAD WITH KHAH", false},
            {"ARABIC LIGATURE DAD WITH KHAH WITH MEEM", false},
            {"ARABIC LIGATURE DAD WITH MEEM", false},
            {"ARABIC LIGATURE DAD WITH REH", false},
            {"ARABIC LIGATURE DAD WITH YEH", false},
            {"ARABIC LIGATURE FEH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE FEH WITH HAH", false},
            {"ARABIC LIGATURE FEH WITH JEEM", false},
            {"ARABIC LIGATURE FEH WITH KHAH", false},
            {"ARABIC LIGATURE FEH WITH KHAH WITH MEEM", false},
            {"ARABIC LIGATURE FEH WITH MEEM", false},
            {"ARABIC LIGATURE FEH WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE FEH WITH YEH", false},
            {"ARABIC LIGATURE GHAIN WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE GHAIN WITH JEEM", false},
            {"ARABIC LIGATURE GHAIN WITH MEEM", false},
            {"ARABIC LIGATURE GHAIN WITH MEEM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE GHAIN WITH MEEM WITH MEEM", false},
            {"ARABIC LIGATURE GHAIN WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE GHAIN WITH YEH", false},
            {"ARABIC LIGATURE HAH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE HAH WITH JEEM", false},
            {"ARABIC LIGATURE HAH WITH JEEM WITH YEH", false},
            {"ARABIC LIGATURE HAH WITH MEEM", false},
            {"ARABIC LIGATURE HAH WITH MEEM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE HAH WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE HAH WITH YEH", false},
            {"ARABIC LIGATURE HEH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE HEH WITH JEEM", false},
            {"ARABIC LIGATURE HEH WITH MEEM", false},
            {"ARABIC LIGATURE HEH WITH MEEM WITH JEEM", false},
            {"ARABIC LIGATURE HEH WITH MEEM WITH MEEM", false},
            {"ARABIC LIGATURE HEH WITH SUPERSCRIPT ALEF", false},
            {"ARABIC LIGATURE HEH WITH YEH", false},
            {"ARABIC LIGATURE JEEM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE JEEM WITH HAH", false},
            {"ARABIC LIGATURE JEEM WITH HAH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE JEEM WITH HAH WITH YEH", false},
            {"ARABIC LIGATURE JEEM WITH MEEM", false},
            {"ARABIC LIGATURE JEEM WITH MEEM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE JEEM WITH MEEM WITH HAH", false},
            {"ARABIC LIGATURE JEEM WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE JEEM WITH YEH", false},
            {"ARABIC LIGATURE KAF WITH ALEF", false},
            {"ARABIC LIGATURE KAF WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE KAF WITH HAH", false},
            {"ARABIC LIGATURE KAF WITH JEEM", false},
            {"ARABIC LIGATURE KAF WITH KHAH", false},
            {"ARABIC LIGATURE KAF WITH LAM", false},
            {"ARABIC LIGATURE KAF WITH MEEM", false},
            {"ARABIC LIGATURE KAF WITH MEEM WITH MEEM", false},
            {"ARABIC LIGATURE KAF WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE KAF WITH YEH", false},
            {"ARABIC LIGATURE KHAH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE KHAH WITH HAH", false},
            {"ARABIC LIGATURE KHAH WITH JEEM", false},
            {"ARABIC LIGATURE KHAH WITH MEEM", false},
            {"ARABIC LIGATURE KHAH WITH YEH", false},
            {"ARABIC LIGATURE LAM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE LAM WITH HAH", false},
            {"ARABIC LIGATURE LAM WITH HAH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE LAM WITH HAH WITH MEEM", false},
            {"ARABIC LIGATURE LAM WITH HAH WITH YEH", false},
            {"ARABIC LIGATURE LAM WITH HEH", false},
            {"ARABIC LIGATURE LAM WITH JEEM", false},
            {"ARABIC LIGATURE LAM WITH JEEM WITH JEEM", false},
            {"ARABIC LIGATURE LAM WITH JEEM WITH MEEM", false},
            {"ARABIC LIGATURE LAM WITH JEEM WITH YEH", false},
            {"ARABIC LIGATURE LAM WITH KHAH", false},
            {"ARABIC LIGATURE LAM WITH KHAH WITH MEEM", false},
            {"ARABIC LIGATURE LAM WITH MEEM", false},
            {"ARABIC LIGATURE LAM WITH MEEM WITH HAH", false},
            {"ARABIC LIGATURE LAM WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE LAM WITH YEH", false},
            {"ARABIC LIGATURE MEEM WITH ALEF", false},
            {"ARABIC LIGATURE MEEM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE MEEM WITH HAH", false},
            {"ARABIC LIGATURE MEEM WITH HAH WITH JEEM", false},
            {"ARABIC LIGATURE MEEM WITH HAH WITH MEEM", false},
            {"ARABIC LIGATURE MEEM WITH HAH WITH YEH", false},
            {"ARABIC LIGATURE MEEM WITH JEEM", false},
            {"ARABIC LIGATURE MEEM WITH JEEM WITH HAH", false},
            {"ARABIC LIGATURE MEEM WITH JEEM WITH KHAH", false},
            {"ARABIC LIGATURE MEEM WITH JEEM WITH MEEM", false},
            {"ARABIC LIGATURE MEEM WITH JEEM WITH YEH", false},
            {"ARABIC LIGATURE MEEM WITH KHAH", false},
            {"ARABIC LIGATURE MEEM WITH KHAH WITH JEEM", false},
            {"ARABIC LIGATURE MEEM WITH KHAH WITH MEEM", false},
            {"ARABIC LIGATURE MEEM WITH KHAH WITH YEH", false},
            {"ARABIC LIGATURE MEEM WITH MEEM", false},
            {"ARABIC LIGATURE MEEM WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE MEEM WITH YEH", false},
            {"ARABIC LIGATURE NOON WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE NOON WITH HAH", false},
            {"ARABIC LIGATURE NOON WITH HAH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE NOON WITH HAH WITH MEEM", false},
            {"ARABIC LIGATURE NOON WITH HAH WITH YEH", false},
            {"ARABIC LIGATURE NOON WITH HEH", false},
            {"ARABIC LIGATURE NOON WITH JEEM", false},
            {"ARABIC LIGATURE NOON WITH JEEM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE NOON WITH JEEM WITH HAH", false},
            {"ARABIC LIGATURE NOON WITH JEEM WITH MEEM", false},
            {"ARABIC LIGATURE NOON WITH JEEM WITH YEH", false},
            {"ARABIC LIGATURE NOON WITH KHAH", false},
            {"ARABIC LIGATURE NOON WITH MEEM", false},
            {"ARABIC LIGATURE NOON WITH MEEM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE NOON WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE NOON WITH NOON", false},
            {"ARABIC LIGATURE NOON WITH REH", false},
            {"ARABIC LIGATURE NOON WITH YEH", false},
            {"ARABIC LIGATURE NOON WITH ZAIN", false},
            {"ARABIC LIGATURE QAF WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE QAF WITH HAH", false},
            {"ARABIC LIGATURE QAF WITH MEEM", false},
            {"ARABIC LIGATURE QAF WITH MEEM WITH HAH", false},
            {"ARABIC LIGATURE QAF WITH MEEM WITH MEEM", false},
            {"ARABIC LIGATURE QAF WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE QAF WITH YEH", false},
            {"ARABIC LIGATURE QALA USED AS KORANIC STOP SIGN", false},
            {"ARABIC LIGATURE REH WITH SUPERSCRIPT ALEF", false},
            {"ARABIC LIGATURE SAD WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE SAD WITH HAH", false},
            {"ARABIC LIGATURE SAD WITH HAH WITH HAH", false},
            {"ARABIC LIGATURE SAD WITH HAH WITH YEH", false},
            {"ARABIC LIGATURE SAD WITH KHAH", false},
            {"ARABIC LIGATURE SAD WITH MEEM", false},
            {"ARABIC LIGATURE SAD WITH MEEM WITH MEEM", false},
            {"ARABIC LIGATURE SAD WITH REH", false},
            {"ARABIC LIGATURE SAD WITH YEH", false},
            {"ARABIC LIGATURE SALLA USED AS KORANIC STOP SIGN", false},
            {"ARABIC LIGATURE SEEN WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE SEEN WITH HAH", false},
            {"ARABIC LIGATURE SEEN WITH HAH WITH JEEM", false},
            {"ARABIC LIGATURE SEEN WITH HEH", false},
            {"ARABIC LIGATURE SEEN WITH JEEM", false},
            {"ARABIC LIGATURE SEEN WITH JEEM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE SEEN WITH JEEM WITH HAH", false},
            {"ARABIC LIGATURE SEEN WITH KHAH", false},
            {"ARABIC LIGATURE SEEN WITH KHAH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE SEEN WITH KHAH WITH YEH", false},
            {"ARABIC LIGATURE SEEN WITH MEEM", false},
            {"ARABIC LIGATURE SEEN WITH MEEM WITH HAH", false},
            {"ARABIC LIGATURE SEEN WITH MEEM WITH JEEM", false},
            {"ARABIC LIGATURE SEEN WITH MEEM WITH MEEM", false},
            {"ARABIC LIGATURE SEEN WITH REH", false},
            {"ARABIC LIGATURE SEEN WITH YEH", false},
            {"ARABIC LIGATURE SHADDA WITH DAMMA", false},
            {"ARABIC LIGATURE SHADDA WITH DAMMA ISOLATED FORM", false},
            {"ARABIC LIGATURE SHADDA WITH DAMMA MEDIAL FORM", false},
            {"ARABIC LIGATURE SHADDA WITH DAMMATAN ISOLATED FORM", false},
            {"ARABIC LIGATURE SHADDA WITH FATHA", false},
            {"ARABIC LIGATURE SHADDA WITH FATHA ISOLATED FORM", false},
            {"ARABIC LIGATURE SHADDA WITH FATHA MEDIAL FORM", false},
            {"ARABIC LIGATURE SHADDA WITH KASRA", false},
            {"ARABIC LIGATURE SHADDA WITH KASRA ISOLATED FORM", false},
            {"ARABIC LIGATURE SHADDA WITH KASRA MEDIAL FORM", false},
            {"ARABIC LIGATURE SHADDA WITH KASRATAN ISOLATED FORM", false},
            {"ARABIC LIGATURE SHADDA WITH SUPERSCRIPT ALEF", false},
            {"ARABIC LIGATURE SHADDA WITH SUPERSCRIPT ALEF ISOLATED FORM", false},
            {"ARABIC LIGATURE SHEEN WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE SHEEN WITH HAH", false},
            {"ARABIC LIGATURE SHEEN WITH HAH WITH MEEM", false},
            {"ARABIC LIGATURE SHEEN WITH HAH WITH YEH", false},
            {"ARABIC LIGATURE SHEEN WITH HEH", false},
            {"ARABIC LIGATURE SHEEN WITH JEEM", false},
            {"ARABIC LIGATURE SHEEN WITH JEEM WITH YEH", false},
            {"ARABIC LIGATURE SHEEN WITH KHAH", false},
            {"ARABIC LIGATURE SHEEN WITH MEEM", false},
            {"ARABIC LIGATURE SHEEN WITH MEEM WITH KHAH", false},
            {"ARABIC LIGATURE SHEEN WITH MEEM WITH MEEM", false},
            {"ARABIC LIGATURE SHEEN WITH REH", false},
            {"ARABIC LIGATURE SHEEN WITH YEH", false},
            {"ARABIC LIGATURE TAH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE TAH WITH HAH", false},
            {"ARABIC LIGATURE TAH WITH MEEM", false},
            {"ARABIC LIGATURE TAH WITH MEEM WITH HAH", false},
            {"ARABIC LIGATURE TAH WITH MEEM WITH MEEM", false},
            {"ARABIC LIGATURE TAH WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE TAH WITH YEH", false},
            {"ARABIC LIGATURE TEH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE TEH WITH HAH", false},
            {"ARABIC LIGATURE TEH WITH HAH WITH JEEM", false},
            {"ARABIC LIGATURE TEH WITH HAH WITH MEEM", false},
            {"ARABIC LIGATURE TEH WITH HEH", false},
            {"ARABIC LIGATURE TEH WITH JEEM", false},
            {"ARABIC LIGATURE TEH WITH JEEM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE TEH WITH JEEM WITH MEEM", false},
            {"ARABIC LIGATURE TEH WITH JEEM WITH YEH", false},
            {"ARABIC LIGATURE TEH WITH KHAH", false},
            {"ARABIC LIGATURE TEH WITH KHAH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE TEH WITH KHAH WITH MEEM", false},
            {"ARABIC LIGATURE TEH WITH KHAH WITH YEH", false},
            {"ARABIC LIGATURE TEH WITH MEEM", false},
            {"ARABIC LIGATURE TEH WITH MEEM WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE TEH WITH MEEM WITH HAH", false},
            {"ARABIC LIGATURE TEH WITH MEEM WITH JEEM", false},
            {"ARABIC LIGATURE TEH WITH MEEM WITH KHAH", false},
            {"ARABIC LIGATURE TEH WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE TEH WITH NOON", false},
            {"ARABIC LIGATURE TEH WITH REH", false},
            {"ARABIC LIGATURE TEH WITH YEH", false},
            {"ARABIC LIGATURE TEH WITH ZAIN", false},
            {"ARABIC LIGATURE THAL WITH SUPERSCRIPT ALEF", false},
            {"ARABIC LIGATURE THEH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE THEH WITH HEH", false},
            {"ARABIC LIGATURE THEH WITH JEEM", false},
            {"ARABIC LIGATURE THEH WITH MEEM", false},
            {"ARABIC LIGATURE THEH WITH NOON", false},
            {"ARABIC LIGATURE THEH WITH REH", false},
            {"ARABIC LIGATURE THEH WITH YEH", false},
            {"ARABIC LIGATURE THEH WITH ZAIN", false},
            {"ARABIC LIGATURE UIGHUR KIRGHIZ YEH WITH HAMZA ABOVE WITH ALEF MAKSURA", false },  // noqa
            {"ARABIC LIGATURE YEH WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE YEH WITH HAH", false},
            {"ARABIC LIGATURE YEH WITH HAH WITH YEH", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH AE", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ALEF MAKSURA", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH E", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH HAH", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH HEH", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH JEEM", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH KHAH", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH MEEM", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH NOON", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH OE", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH REH", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH U", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH WAW", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH YEH", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH YU", false},
            {"ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH ZAIN", false},
            {"ARABIC LIGATURE YEH WITH HEH", false},
            {"ARABIC LIGATURE YEH WITH JEEM", false},
            {"ARABIC LIGATURE YEH WITH JEEM WITH YEH", false},
            {"ARABIC LIGATURE YEH WITH KHAH", false},
            {"ARABIC LIGATURE YEH WITH MEEM", false},
            {"ARABIC LIGATURE YEH WITH MEEM WITH MEEM", false},
            {"ARABIC LIGATURE YEH WITH MEEM WITH YEH", false},
            {"ARABIC LIGATURE YEH WITH NOON", false},
            {"ARABIC LIGATURE YEH WITH REH", false},
            {"ARABIC LIGATURE YEH WITH YEH", false},
            {"ARABIC LIGATURE YEH WITH ZAIN", false},
            {"ARABIC LIGATURE ZAH WITH MEEM", false},
            // -------------------- End: Ligatures Configurations ------------------- //
        };

        public bool GetBoolean(string key)
        {
            return key switch
            {
                "delete_harakat" => DeleteHarakat,
                "delete_tatweel" => DeleteTatweel,
                "support_zwj" => SupportZwj,
                "shift_harakat_position" => ShiftHarakatPosition,
                "use_unshaped_instead_of_isolated" => UseUnshapedInsteadOfIsolated,
                "support_ligatures" => SupportLigatures,
                _ => EnabledLigatures.TryGetValue(key, out var value) && value
            };
        }
    }
}
